"""empty message

Revision ID: 2b20dae8ede0
Revises: 12d53565d384
Create Date: 2021-08-11 15:12:18.672670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b20dae8ede0'
down_revision = '12d53565d384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rank', sa.String(length=50), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('user', 'rank')
    # ### end Alembic commands ###
