"""empty message

Revision ID: 5900ab1e355d
Revises: 76c7431bbf7e
Create Date: 2021-09-07 13:55:28.902374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5900ab1e355d'
down_revision = '76c7431bbf7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
