"""empty message

Revision ID: d41044f7ec4b
Revises: 781ec828d0a4
Create Date: 2021-09-07 12:19:35.722148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41044f7ec4b'
down_revision = '781ec828d0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('question_a_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_a_id'], ['question_A.id'], name=op.f('fk_comment_question_a_id_question_A')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
